version: "3.8"

services:
  web:
    command: yarn web dev
    build:
      context: ../../
      dockerfile: Dockerfile
      target: "web"
    working_dir: /app
    env_file: "../../services/web/.env.local"
    ports:
      - 3000:3000
    volumes:
      - ../../services/web/src:/app/services/web/src
      - ../../services/web/public:/app/services/web/public
  sse:
    command: node ./services/sse/dist/index.js
    build:
      context: ../../
      dockerfile: Dockerfile
      target: "sse"
    working_dir: /app
    ports:
      - 5353:5353
  peer:
    image: peerjs/peerjs-server
    command: --port 9000 --path /
    ports:
      - 9000:9000
  redis:
    image: redis:6.2.3-alpine
  redis-commender:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
